# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f98bd2f89e44fd2c66e5fe0d16f9424478c7f2f517091ab9e4bb8a39f335b2e2486ef8735b46004e80f2d3b61aa2119219a65805c67aa71d71ec4c0e822eb41d

test:
  secret_key_base: a3c0fbf32a41e5cf6b3a10893a074297731adf7e5aba9d57164fe4efe917b487a59dd4cda717e3c6cf497bedf84b650a110dd695e05aa11e3fdbd222d4a71c2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
